language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aaronpflower/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aaronpflower/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "Docker React"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-623322666961"
  bucket_path: "Docker React"
  on:
    branch: master

access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY
